### test
POST http://localhost:3000/aggregate
Content-Type: application/json

{
    "value": 44.44,
    "obuID": 21312,
    "unix": 837248374
}

### GET invoice 
GET http://localhost:3000/invoice?obu=3311742246723717659

### GET invoice gateway
GET http://localhost:6000/invoice